jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Build and push to Heroku
            command: |
              echo running test
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@1.2
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - deploy