jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Build and push to heroku
          command: |
            heroku login
            heroku git:remote -a audi-rs

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2
version: 2.1

workflows:
  heroku_deploy:
    jobs:
      - deploy



